version: "3.7"

services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        environment: 
            - APP_NAME=FlaskApp
        volumes:
            - './backend:/backend'
        expose:
            - 8080

    frontend:
        build: ./frontend
        container_name:  frontend
        restart: always
        environment: 
            - APP_NAME=VueApp
        ports:
            - "80:80"